#!/bin/sh

## Settings
OUI_FILE="/usr/share/ouidb/oui.csv"

QRY="$1"

if [ -z "$QRY" ]; then
	echo "Usage error: Provide MAC address" >&2
	exit 1
fi

if [ ! -f "$OUI_FILE" ]; then
	echo "OUT DB file doesn't exists" >&2
	exit 2
fi

PREFIX="$(echo "$QRY" | sed -n 's/^\([0-9a-fA-F]\{2\}\)\([:-\.]\{,1\}\)\([0-9a-fA-F]\{2\}\)\2\([0-9a-fA-F]\{2\}\)\2[0-9a-fA-F]\{2\}\2[0-9a-fA-F]\{2\}\2[0-9a-fA-F]\{2\}$/\1\3\4/p')"
[ -n "$PREFIX" ] || exit 3

grep -i "$PREFIX" "$OUI_FILE" 2> /dev/null | cut -d, -f2
